#!/usr/bin/env python3
"""Bundle the modular EA sources into a standalone MQ5 file.

The script reads the main Expert Advisor located at
``src/XAU_Swing_TrendEA_Pro.mq5`` and inlines every include that points to the
``modules`` directory. The generated file lives inside ``dist/`` and can be
copied directly into ``MQL5/Experts`` without bringing the helper modules
alongside it.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_MAIN = ROOT / "src" / "XAU_Swing_TrendEA_Pro.mq5"
MODULES_DIR = ROOT / "src" / "modules"
DIST_FILE = ROOT / "dist" / "XAU_Swing_TrendEA_Pro.mq5"
MODULE_INCLUDE_RE = re.compile(r'^#include\s+"modules/([^"]+)"')


HEADER = """// -----------------------------------------------------------------------------
// AUTOGENERATED FILE – DO NOT EDIT DIRECTLY.
// Source: src/XAU_Swing_TrendEA_Pro.mq5 + src/modules/* (inlined).
// This bundled version exists for MetaTrader terminals where copying the
// accompanying modules directory is inconvenient. Developers should keep editing
// the modular sources under src/ and regenerate this bundle via
// ``python tools/bundle_ea.py`` when publishing a release.
// -----------------------------------------------------------------------------
"""


def build_bundle() -> str:
    if not SRC_MAIN.exists():
        raise SystemExit(f"Main source file not found: {SRC_MAIN}")
    if not MODULES_DIR.exists():
        raise SystemExit(f"Modules directory not found: {MODULES_DIR}")

    output_lines = [HEADER]
    for line in SRC_MAIN.read_text(encoding="utf-8").splitlines():
        match = MODULE_INCLUDE_RE.match(line.strip())
        if match:
            module_name = match.group(1)
            module_path = MODULES_DIR / module_name
            if not module_path.exists():
                raise SystemExit(f"Missing module: {module_path}")
            output_lines.append(f"// --- BEGIN inlined module: modules/{module_name} ---")
            output_lines.extend(module_path.read_text(encoding="utf-8").splitlines())
            output_lines.append(f"// --- END inlined module: modules/{module_name} ---")
            output_lines.append("")
        else:
            output_lines.append(line)
    output_lines.append("")
    return "\n".join(output_lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DIST_FILE,
        help="Override the default dist/XAU_Swing_TrendEA_Pro.mq5 path.",
    )
    args = parser.parse_args()

    bundle = build_bundle()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(bundle, encoding="utf-8")
    print(f"Standalone Expert Advisor written to {args.output}")


if __name__ == "__main__":
    main()
